export default [
          "bleed",
          "blind",
          "confuse",
          "daze",
          "dazzle",
          "deaf",
          "disease",
          "energyDrain",
          "fatigue",
          "fear",
          "mindAffecting",
          "poison",
          "sicken",
          "paralyze",
          "petrify",
          "stun",
          "sleep"
        ]