export default {
    "acrobatics": "acr",
    "artistry": "art",
    "appraise": "apr",
    "bluff": "blf",
    "climb": "clm",
    "craft": "crf",
    "diplomacy": "dip",
    "disable device": "dev",
    "disguise": "dis",
    "escape artist": "esc",
    "fly": "fly",
    "handle animal": "han",
    "heal": "hea",
    "intimidate": "int",
    "knowledge": {
        "arcana": "kar",
        "dungeoneering": "kdu",
        "engineering": "ken",
        "geography": "kge",
        "history": "khi",
        "local": "klo",
        "nature": "kna",
        "nobility": "kno",
        "planes": "kpl",
        "religion": "kre"
    },
    "linguistics": "lin",
    "lore": "lor",
    "perception": "per",
    "perform": "prf",
    "profession": "pro",
    "ride": "rid",
    "sense motive": "sen",
    "sleight of hand": "slt",
    "spellcraft": "spl",
    "stealth": "ste",
    "survival": "sur",
    "swim": "swm",
    "use magic device": "umd"
}