export default [
    "Adept",
    "Agent of the Grave",
    "Alchemist",
    "Aldori Swordlord",
    "Antipaladin",
    "Arcane Archer",
    "Arcane Trickster",
    "Arcanist",
    "Arclord of Nex",
    "Argent Dramaturge",
    "Aristocrat",
    "Asavir",
    "Ashavic Dancer",
    "Aspis Agent",
    "Assassin",
    "Barbarian",
    "Bard",
    "Battle Herald",
    "Bellflower Tiller",
    "Blackfire Adept",
    "Bloatmage",
    "Bloodrager",
    "Brawler",
    "Brewkeeper",
    "Brother of the Seal",
    "Cavalier",
    "Champion of Irori",
    "Chernasardo Warden",
    "Cleric",
    "Commoner",
    "Crimson Templar",
    "Cyphermage",
    "Daggermark Poisoner",
    "Daivrat",
    "Darechaser",
    "Dawnflower Anchorite",
    "Dawnflower Dissident",
    "Death Slayer",
    "Demoniac",
    "Devoted Muse",
    "Diabolist",
    "Divine Scion",
    "Dragon Disciple",
    "Druid",
    "Duelist",
    "Eldritch Knight",
    "Enchanting Courtesan",
    "Envoy of Balance",
    "Esoteric Knight",
    "Evangelist",
    "Exalted",
    "Expert",
    "Feysworn",
    "Fighter",
    "Genie Binder",
    "Golden Legionnaire",
    "Gray Corsair",
    "Gray Gardener",
    "Green Faith Acolyte",
    "Gunslinger",
    "Halfling Opportunist",
    "Harrower",
    "Hellknight Signifer",
    "Hellknight",
    "Heritor Knight",
    "Hinterlander",
    "Holy Vindicator",
    "Horizon Walker",
    "Hunter",
    "Inheritor's Crusader",
    "Inner Sea Pirate",
    "Inquisitor",
    "Investigator",
    "Kineticist",
    "Knight of Ozem",
    "Lantern Bearer",
    "Lion Blade",
    "Living Monolith",
    "Loremaster",
    "Low Templar",
    "Magaambyan Arcanist",
    "Magus",
    "Mammoth Rider",
    "Master Chymist",
    "Master Spy",
    "Medium",
    "Mesmerist",
    "Monk",
    "Mortal Usher",
    "Mystery Cultist",
    "Mystic Theurge",
    "Nature Warden",
    "Ninja",
    "Noble Scion",
    "Occultist",
    "Omdura",
    "Oracle",
    "Pain Taster",
    "Paladin",
    "Pathfinder Chronicler",
    "Pathfinder Delver",
    "Pathfinder Field Agent",
    "Pathfinder Savant",
    "Pit Fighter",
    "Proctor",
    "Prophet of Kalistrade",
    "Psychic",
    "Pure Legion Enforcer",
    "Rage Prophet",
    "Ranger",
    "Razmiran Priest",
    "Red Mantis Assassin",
    "Riftwarden",
    "Ritualist",
    "Rivethun Emissary",
    "Rogue",
    "Rose Warden",
    "Runeguard",
    "Sacred Sentinel",
    "Samurai",
    "Sanguine Angel",
    "Scar Seeker",
    "Sentinel",
    "Shadowdancer",
    "Shaman",
    "Shieldmarshal",
    "Shifter",
    "Skald",
    "Skyseeker",
    "Slayer",
    "Sleepless Detective",
    "Sorcerer",
    "Soul Warden",
    "Souldrinker",
    "Sphere Singer",
    "Spiritualist",
    "Stalwart Defender",
    "Stargazer",
    "Steel Falcon",
    "Storm Kindler",
    "Student of Perfection",
    "Student of War",
    "Summoner",
    "Swashbuckler",
    "Tattooed Mystic",
    "Technomancer",
    "Thuvian Alchemist",
    "Twilight Talon",
    "Ulfen Guard",
    "Umbral Court Agent",
    "Vampire Hunter",
    "Veiled Illusionist",
    "Vigilante",
    "Warpriest",
    "Warrior",
    "Westcrown Devil",
    "Winter Witch",
    "Witch",
    "Wizard",
    "abjurer",
    "conjurer",
    "diviner",
    "enchanter",
    "evoker",
    "illusionist",
    "necromancer",
    "transmuter",
    "universalist"
];