export default [
    "Aasimar",
    "Adaro",
    "Android",
    "Aphorite",
    "Aquatic Elf",
    "Astomoi",
    "Caligni",
    "Catfolk",
    "Cecaelia",
    "Changeling",
    "Deep One Hybrid",
    "Dhampir",
    "Drow",
    "Drow Noble",
    "Duergar",
    "Duskwalker",
    "Dwarf",
    "Elf",
    "Fetchling",
    "Ganzi",
    "Gathlain",
    "Ghoran",
    "Gillmen",
    "Gnoll",
    "Gnome",
    "Goblin",
    "Green Martian",
    "Grindylow",
    "Grippli",
    "Half-Elf",
    "Half-Orc",
    "Halfling",
    "Hobgoblin",
    "Human",
    "Ifrit",
    "Kasatha",
    "Kitsune",
    "Kobold",
    "Kuru",
    "Lashunta (Female)",
    "Lashunta (Male)",
    "Lizardfolk",
    "Locathah",
    "Merfolk",
    "Monkey Goblin",
    "Munavri",
    "Nagaji",
    "Naiad",
    "Ogre",
    "Orang-Pendak",
    "Orc",
    "Oread",
    "Ratfolk",
    "Reborn Samsaran",
    "Reptoid",
    "Rougarou",
    "Sahuagin",
    "Samsaran",
    "Shabti",
    "Skinwalker",
    "Strix",
    "Suli",
    "Svirfneblin",
    "Sylph",
    "Syrinx",
    "Tengu",
    "Tiefling",
    "Triaxian",
    "Triton",
    "Trox",
    "Undine",
    "Vanara",
    "Vine Leshy",
    "Vishkanya",
    "Wayang",
    "Wyrwood",
    "Wyvaran",
    "Yaddithian"
]